# Generated by Django 2.1.2 on 2018-10-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_nmapscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nmapscan',
            name='target',
            field=models.CharField(max_length=4048),
        ),
    ]
