# Generated by Django 2.1.2 on 2018-10-16 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='articles',
            field=models.ForeignKey(on_delete=True, related_name='comments', to='articles.Articles'),
        ),
    ]
